export const START_GET_EXPRESS_LIST = 'START_GET_EXPRESS_LIST';
export const GET_EXPRESS_LIST = 'GET_EXPRESS_LIST';
export const GET_EXPRESS_INFO = 'GET_EXPRESS_INFO';
export const SET_EXPRESS_LIST = 'SET_EXPRESS_LIST';
export const DEL_EXPRESS = 'DEL_EXPRESS';
export const ADD_EXPRESS = 'ADD_EXPRESS';
export const EDIT_EXPRESS = 'EDIT_EXPRESS';
export const SET_EXPRESS_IS_COMMONLY_USE = 'SET_EXPRESS_IS_COMMONLY_USE';