export const START_GET_FREIGHT_LIST = 'START_GET_FREIGHT_LIST';
export const GET_FREIGHT_LIST = 'GET_FREIGHT_LIST';
export const GET_FREIGHT_INFO = 'GET_FREIGHT_INFO';
export const SET_FREIGHT_LIST = 'SET_FREIGHT_LIST';
export const DEL_FREIGHT = 'DEL_FREIGHT';
export const ADD_FREIGHT = 'ADD_FREIGHT';
export const EDIT_FREIGHT = 'EDIT_FREIGHT';
