export const START_GET_SHIPPER_LIST = 'START_GET_SHIPPER_LIST';
export const GET_SHIPPER_LIST = 'GET_SHIPPER_LIST';
export const GET_SHIPPER_INFO = 'GET_SHIPPER_INFO';
export const SET_SHIPPER_LIST = 'SET_SHIPPER_LIST';
export const DEL_SHIPPER = 'DEL_SHIPPER';
export const ADD_SHIPPER = 'ADD_SHIPPER';
export const EDIT_SHIPPER = 'EDIT_SHIPPER';
