import { fork } from 'redux-saga/effects';
import member from './member';
import app from './app';
import auth from './auth';
import authMember from './auth/member';
import authRole from './auth/role';
import goods from './goods';
import goodsCategory from './goods/category';
import photoGallery from './app/photoGallery';
import wechat from './wechat';
import wechatAutoReply from './wechat/autoReply';
import wechatUser from './wechat/user';
import wechatUserTags from './wechat/userTags';
import message from './wechat/message';
import material from './wechat/material';
import goodsSpec from './goods/spec';
import shippingTemplate from './setting/shippingTemplate';
import setting from './setting';
import shop from './shop';
import shopDecorate from './shop/decorate';
import orderRefund from './order/refund';
import order from './order';
import orderEvaluate from './order/evaluate';
import statistics from './statistics';
import shipper from './deliver/shipper';
import express from './deliver/express';
import freight from './deliver/freight';
import user from './user';


export default function* rootSaga() {
    yield fork(statistics);
    yield fork(member);
    yield fork(app);
    yield fork(auth);
    yield fork(authMember);
    yield fork(authRole);
    yield fork(goods);
    yield fork(goodsCategory);
    yield fork(photoGallery);
    yield fork(wechat);
    yield fork(wechatAutoReply);
    yield fork(wechatUser);
    yield fork(wechatUserTags);
    yield fork(message);
    yield fork(material);
    yield fork(goodsSpec);
    yield fork(shippingTemplate);
    yield fork(setting);
    yield fork(shop);
    yield fork(shopDecorate);
    yield fork(orderRefund);
    yield fork(order);
    yield fork(orderEvaluate);
    yield fork(shipper);
    yield fork(express);
    yield fork(freight);
    yield fork(user);
}
