import { env } from '../root';
const ROOT_URL = `${env.domain}/admin/`;
export const WechatApi = {
    getConf:{
        url: `${ROOT_URL}wechat/getConf`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    checkApiStatus:{
        url: `${ROOT_URL}wechat/checkApiStatus`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    confSet:{
        url: `${ROOT_URL}wechat/confSet`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    menuList:{
        url: `${ROOT_URL}wechat/menuList`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    menuCurrent:{
        url: `${ROOT_URL}wechat/menuCurrent`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    menuCreate:{
        url: `${ROOT_URL}wechat/menuCreate`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    menuDelete:{
        url: `${ROOT_URL}wechat/menuDelete`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    autoReplyStatusSet:{
        url: `${ROOT_URL}wechat/autoReplyStatusSet`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    autoReplyStatusGet:{
        url: `${ROOT_URL}wechat/autoReplyStatusGet`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    autoReplySubscribeGet:{
        url: `${ROOT_URL}wechat/autoReplySubscribeGet`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    autoReplySubscribeSet:{
        url: `${ROOT_URL}wechat/autoReplySubscribeSet`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    replyKeywordsList:{
        url: `${ROOT_URL}wechat/replyKeywordsList`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    autoReplyKeywordsAdd:{
        url: `${ROOT_URL}wechat/autoReplyKeywordsAdd`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    autoReplyKeywordsEdit:{
        url: `${ROOT_URL}wechat/autoReplyKeywordsEdit`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    autoReplyKeywordsDel:{
        url: `${ROOT_URL}wechat/autoReplyKeywordsDel`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    autoReplyKeywordsInfo:{
        url: `${ROOT_URL}wechat/autoReplyKeywordsInfo`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userList:{
        url: `${ROOT_URL}wechat/userList`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userBlackList:{
        url: `${ROOT_URL}wechat/userBlackList`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userSelect:{
        url: `${ROOT_URL}wechat/userSelect`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userBlock:{
        url: `${ROOT_URL}wechat/userBlock`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userUnblock:{
        url: `${ROOT_URL}wechat/userUnblock`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userRemark:{
        url: `${ROOT_URL}wechat/userRemark`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userTagList:{
        url: `${ROOT_URL}wechat/userTagList`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    getToken:{
        url: `${ROOT_URL}wechat/getToken`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userTagCreate:{
        url: `${ROOT_URL}wechat/userTagCreate`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userTagUpdate:{
        url: `${ROOT_URL}wechat/userTagUpdate`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userTagDelete:{
        url: `${ROOT_URL}wechat/userTagDelete`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userTagsByOpenid:{
        url: `${ROOT_URL}wechat/userTagsByOpenid`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userTagUsersOfTag:{
        url: `${ROOT_URL}wechat/userTagUsersOfTag`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    userTagTagUsers:{
        url: `${ROOT_URL}wechat/userTagTagUsers`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    userTagUntagUsers:{
        url: `${ROOT_URL}wechat/userTagUntagUsers`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    broadcastRecords:{
        url: `${ROOT_URL}wechat/broadcastRecords`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    broadcastUserSearch:{
        url: `${ROOT_URL}wechat/broadcastUserSearch`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    broadcastCreate:{
        url: `${ROOT_URL}wechat/broadcastCreate`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    broadcastSurplus:{
        url: `${ROOT_URL}wechat/broadcastSurplus`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    broadcastRecordsDel:{
        url: `${ROOT_URL}wechat/broadcastRecordsDel`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialList:{
        url: `${ROOT_URL}wechat/materialList`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    materialUploadThumb:{
        url: `${ROOT_URL}wechat/materialUploadThumb`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialUploadArticle:{
        url: `${ROOT_URL}wechat/materialUploadArticle`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialUpdateArticle:{
        url: `${ROOT_URL}wechat/materialUpdateArticle`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialGet:{
        url: `${ROOT_URL}wechat/materialGet`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    materialUploadArticleImage:{
        url: `${ROOT_URL}wechat/materialUploadArticleImage`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialUploadImage:{
        url: `${ROOT_URL}wechat/materialUploadImage`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialUploadVoice:{
        url: `${ROOT_URL}wechat/materialUploadVoice`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialUploadVideo:{
        url: `${ROOT_URL}wechat/materialUploadVideo`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    localNews:{
        url: `${ROOT_URL}wechat/localNews`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    localNewsInfo:{
        url: `${ROOT_URL}wechat/localNewsInfo`,
        method: 'GET',
        showLoading: false,
        needLogin: true,
    },
    localNewsAdd:{
        url: `${ROOT_URL}wechat/localNewsAdd`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    localNewsEdit:{
        url: `${ROOT_URL}wechat/localNewsEdit`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    localNewsDel:{
        url: `${ROOT_URL}wechat/localNewsDel`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    },
    materialDelete:{
        url: `${ROOT_URL}wechat/materialDelete`,
        method: 'POST',
        showLoading: false,
        needLogin: true,
    }
}
